#
# Project configuration
#
# Environment specific settings can be overridden in:
# /config/settings/<environment>.yml
# 

# Name of the installation
name: "Ontohub Staging"

# Hostname of the installation
hostname: staging.ontohub.org

# Optional asset host for delivery of static files (css, images, javascripts)
# asset_host: assets.example.com

# Sender address for outgoing mail
email: noreply@staging.ontohub.org

# Mail delivery
# http://guides.rubyonrails.org/action_mailer_basics.html#action-mailer-configuration
action_mailer:
  delivery_method: sendmail

# The number of days a user can access
# the website without confirming his account.
allow_unconfirmed_access_for_days: 3

# Footer links and texts
footer:
  - text: Imprint
    href: http://about.ontohub.org/
  - text: Source Code
    href: https://github.com/ontohub/ontohub

# Delivery of exceptions, disabled by default
exception_notifier:
  enabled: true
  email_prefix: "[ontohub staging exception]"
  sender_address: "exceptions@ontohub.org"
  exception_recipients:
    - exception-recipient@example.com
