#
# Project configuration
#
# Environment specific settings can be overridden in:
# /config/settings/<environment>.yml
# 

# Name of the installation
name: "Ontohub"

# Hostname of the installation
hostname: ontohub.org

# Optional asset host for delivery of static files (css, images, javascripts)
# asset_host: assets.example.com

# Sender address for outgoing mail
email: noreply@ontohub.org

# Mail delivery
# http://guides.rubyonrails.org/action_mailer_basics.html#action-mailer-configuration
action_mailer:
  delivery_method: sendmail

# The number of days a user can access
# the website without confirming his account.
allow_unconfirmed_access_for_days: 3

# Footer links and texts
footer:
  - text: Copyright © 2012, 2013 Universität Bremen
  - text: Released under the terms of GNU AGPL 3.0
    href: http://www.gnu.org/licenses/agpl-3.0.html
  - text: Ontohub code on GitHub
    href: https://github.com/ontohub/ontohub
  - text: About
    href: http://about.ontohub.org

# Delivery of exceptions, disabled by default
exception_notifier:
  enabled: false
  email_prefix: "[ontohub exception]"
  sender_address: "exceptions@ontohub.org"
  exception_recipients:
    - exceptions@ontohub.org
